# =============================================================================
# OPA Configuration — Bundle from Azure Blob Storage (SAS Token)
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: opa-system
data:
  opa-config.yaml: |
    services:
      azure_blob:
        url: https://stgitopscanaryd44eb2.blob.core.windows.net
        headers:
          x-ms-version: "2020-04-08"
        response_header_timeout_seconds: 10

    bundles:
      authz:
        service: azure_blob
        resource: "opa-bundles/bundle.tar.gz?se=2027-12-31&sp=r&sv=2026-02-06&sr=c&sig=QE43o7yTCkOh1xBxGzD5oSldfsmXZthntE1myR1rD6c%3D"
        persist: true
        polling:
          min_delay_seconds: 30
          max_delay_seconds: 60

    decision_logs:
      console: true
