# =============================================================================
# ServiceMonitor — Spring Boot (for Prometheus scraping)
# =============================================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: app
  labels:
    app: spring-boot
    release: monitoring    # must match kube-prometheus-stack release name
spec:
  selector:
    matchLabels:
      app: spring-boot
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
# =============================================================================
# ServiceMonitor — APISIX Prometheus Metrics
# =============================================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apisix-monitor
  namespace: ingress-apisix
  labels:
    app: apisix
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
  namespaceSelector:
    matchNames:
      - ingress-apisix
  endpoints:
    - port: prometheus
      path: /apisix/prometheus/metrics
      interval: 15s
      scrapeTimeout: 10s
