# =============================================================================
# Spring Boot — External Service (LoadBalancer, for direct debug access)
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-external
  namespace: app
  labels:
    app: spring-boot
spec:
  type: LoadBalancer
  selector:
    app: spring-boot
    version: stable
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
